export const FETCH_CHARACTERS_BEGIN   = 'FETCH_CHARACTERS_BEGIN';
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_FAILURE = 'FETCH_CHARACTERS_FAILURE';
export const FETCH_All_CHARACTERS     = "FETCH_All_CHARACTERS";

export const FILTER_CHARACTERS     = "FILTER_CHARACTERS";
export const SORT_CHARACTERS     = "SORT_CHARACTERS";
export const SEARCH_CHARACTERS     = "SEARCH_CHARACTERS";
